permissions:
  ban-use: "valkya.ban.use"
  ban-perm-use: "valkya.ban.perm"
  ban-bypass: "valkya.ban.bypass"
  unban-use: "valkya.unban.use"
  kick-use: "valkya.kick.use"
  kick-bypass: "valkya.kick.bypass"
  check-use: "valkya.check.use"
  mute-use: "valkya.mute.use"
  mute-perm-use: "valkya.mute.perm"
  mute-bypass: "valkya.mute.bypass"
  unmute-use: "valkya.unmute.use"
  getmat-use: "valkya.getmat.use"
  xpbottle-use: "valkya.xpbottle.use"
  xpbottle-give: "valkya.xpbottle.give"
  xp-death: "valkya.xp.death"
  cooldownchat-bypass: "valkya.cooldownchat.bypass"
  cooldownchat-modif: "valkya.cooldownchat.modif"
  report-use: "valkya.report.use"
  report-receive: "valkya.report.receive"
  moderation-chat: "valkya.moderation.chat"
  gamemode-change: "valkya.gamemode.change"
  gamemode-change-other: "valkya.gamemode.changeother"
  gamemode-notify: "valkya.gamemode.notify"
  kdr-use: "valkya.kdr.use"
  repair-hand: "valkya.repair.hand"
  repair-all: "valkya.repair.all"
  repair-bypass-cooldown: "valkya.repair.bypass.cooldown"
  broadcast-use: "valkya.broadcast.use"
  rtp-use: "valkya.rtp.use"
  chat-off-bypass: "valkya.chat.bypass"
  chat-changeset-use: "valkya.chat.change"
  chat-clear: "valkya.chat.clear"

chat: true

rtp:
  world: world
  x: 2000
  z: 2000
  cooldown-active: true
  cooldown-temps: 3600

sql:
  host: "localhost"
  database: "valkya"
  user: "root"
  pass: ""
  port: "3306"