messages:
  no-player: "Vous devez être un joueur pour executer cette commande !"
  no-perm: "&cVous n'avez pas la permission d'executer cette commande !"

permissions:
  staff-use: "valorion.use"
  ban-use: "valorion.ban.use"
  ban-perm-use: "valorion.ban.perm"
  ban-bypass: "valorion.ban.bypass"
  unban-use: "valorion.unban.use"
  kick-use: "valorion.kick.use"
  kick-bypass: "valorion.kick.bypass"
  check-use: "valorion.check.use"
  mute-use: "valorion.mute.use"
  mute-perm-use: "valorion.mute.perm"
  mute-bypass: "valorion.mute.bypass"
  unmute-use: "valorion.unmute.use"
  getmat-use: "valorion.getmat.use"
  xpbottle-use: "valorion.xpbottle.use"
  xpbottle-give: "valorion.xpbottle.give"
  xp-death: "valorion.xp.death"
  cooldownchat-bypass: "valorion.cooldownchat.bypass"
  cooldownchat-modif: "valorion.cooldownchat.modif"
  #staffmode-use: "valorion.staffmode.use"
  report-use: "valorion.report.use"
  report-receive: "valorion.report.receive"
  moderation-chat: "valorion.moderation.chat"
  failles-use: "valorion.failles.use"

sql:
  host: "localhost"
  database: "valorion"
  user: "root"
  pass: ""
  port: "3306"