name: ValkyaCore
main: fr.volax.valkyacore.ValkyaCore
version: 1.1.14
author: Volax
depend: [WorldGuard, Vault, VolaxAPI]
description: ValkyaCore plugin for Valkya
commands:
  ban:
    description: Bannir un joueur
  unban:
    description: Débannir un joueur
  kick:
    description: Kick un joueur
  check:
    description: Avoir les informations de sanctions d'un joueur
  mute:
    description: Mute un joueur
  unmute:
    description: Démute un joueur
  getmat:
    description: Avoir le nom d'un bloc
  xpbottle:
    description: Bouteille d'xp
  ec:
    description: Enderchest portable
    aliases: [enderchest]
  report:
    description: Report un joueur
  gamemode:
    aliases: [gm]
    description: Gamemode commande
  gmc:
      description: Aliases gamemode creatif commande
  gms:
      description: Aliases gamemode survie commande
  gma:
      description: Aliases gamemode aventure commande
  kd:
    description: KD commande
  repair:
    description: Repair commande
  broadcast:
    aliases: [bc]
    description: Broadcast commande
  rtp:
    aliases: [randomtp]
    description: RTP commande
  vchat:
    description: Chat commande
  combat:
    description: Combat commande
  kickall:
    description: Kickall commande
  checker:
    description: Checker commande
  valkyaconfigreload:
    aliases: [vcr]
    description: ValkyaConfigReload
  staffmod:
    description: Staffmod command
  staffmodlist:
    description: Staffmodlist command
  reportlog:
    description: ReportLog command
  spawners:
    aliases: [spawner]
    description: Spawners command