name: ValkyaCore
main: fr.volax.valkyacore.ValkyaCore
version: 1.0.04a
author: Volax
description: ValkyaCore plugin for Valkya
commands:
  staff:
    description: Aide du ValkyaCore
  ban:
    description: Bannir un joueur
  unban:
    description: Débannir un joueur
  kick:
    description: Kick un joueur
  check:
    description: Avoir les informations de sanctions d'un joueur
  mute:
    description: Mute un joueur
  unmute:
    description: Démute un joueur
  getmat:
    description: Avoir le nom d'un bloc
  xpbottle:
    description: Bouteille d'xp
  ec:
    description: Enderchest portable
    aliases: [enderchest]
  report:
    description: Report un joueur
  gamemode:
    description: Gamemode commande
